name: twparker
favicon: null
layout_spectrum: 0.99445
typography_spectrum: 0.79278
title: Thomas W. Parker III
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75684570-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41414289944805205
  lightness: 0.10424721892923117
  saturation: 0.4311096868477762
  rhythmicContrast: 0.8800868897233158
purpose: []
